name: Modified CI
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - '8'
          - '11'
          - '17'
          - '21'
        compiler:
          - javac
          - ecj
        extra:
          - none
          - errorprone
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: print Java version
        run: java -version
      - name: Run tests
        run: mvn --batch-mode --no-transfer-progress clean test -P${{ matrix.compiler
          }} -Dextra=${{ matrix.extra }} "-Dfailsafe.reports=false" "-Dmaven.surefire.reports.skip=true"
          "-Dsurefire.useFile=false" "-Dsurefire.reportDirectory=target/surefire-reports-empty"
          "-Dmaven.surefire.reportFormat=none" "-Dtest.skip=true" "-DskipTests=false"
          "-Dmaven.surefire.skip=true"
    name: build (${{ matrix.java }}, ${{ matrix.compiler }}, ${{ matrix.extra }})
'on':
  - push
  - workflow_dispatch
